# Generated by Django 5.2.5 on 2026-03-11 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_client_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseorder',
            options={'ordering': ['-order_date']},
        ),
        migrations.AddField(
            model_name='caseorder',
            name='order_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseorder',
            name='hearing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cases.hearing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseorder',
            name='order_type',
            field=models.CharField(choices=[('interim', 'Interim Order'), ('final', 'Final Judgment'), ('stay', 'Stay Order'), ('direction', 'Court Direction')], max_length=20),
        ),
    ]
