# Generated by Django 5.2.5 on 2026-04-16 06:35

import cases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_caseorder_options_caseorder_order_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PET', 'Petition'), ('EVI', 'Evidence'), ('ORD', 'Court Order'), ('CLI', 'Client Document'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cases.models.get_upload_path)),
                ('version_number', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cases.casedocument')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
    ]
