# Generated by Django 5.2.5 on 2026-04-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_court_firm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='firm',
        ),
    ]
