# Generated by Django 5.2.5 on 2026-04-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_assigned_senior_lawyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='judge_observations',
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
