# Generated by Django 5.2.5 on 2026-04-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_remove_case_judge_remove_hearing_judge_observations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='hearing_documents/'),
        ),
    ]
