# Generated by Django 5.2.5 on 2026-04-30 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_hearing_document'),
        ('firms', '0002_firm_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='case_docs/'),
        ),
        migrations.AddField(
            model_name='case',
            name='first_hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('case_id', models.CharField(blank=True, max_length=100, null=True)),
                ('court', models.CharField(blank=True, max_length=255, null=True)),
                ('court_outcome', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_histories', to='firms.firm')),
            ],
        ),
    ]
