# Generated by Django 5.2.5 on 2026-04-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_case_doc_case_first_hearing_date_case_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistory',
            name='document',
            field=models.FileField(blank=True, help_text='Upload Excel, PDF, Word, or CSV files here', null=True, upload_to='case_history_docs/'),
        ),
    ]
