# Generated by Django 5.2.5 on 2026-05-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_casehistory_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistory',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
