# Generated by Django 5.2.5 on 2026-06-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_alter_casehistory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('pending', 'Pending'), ('arguments', 'Arguments'), ('reserved', 'Reserved for Judgment'), ('decided', 'Decided'), ('closed', 'Closed'), ('stayed', 'Stayed')], default='filed', max_length=20),
        ),
    ]
