# Generated by Django 5.2.5 on 2026-04-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_court_firm'),
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_firms', to='cases.court'),
        ),
    ]
