# Generated by Django 5.2.5 on 2026-06-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal_library', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Judgment',
        ),
    ]
