# Generated by Django 5.2.5 on 2026-06-20 14:34

import django.db.models.deletion
import legal_library.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_library', '0002_delete_judgment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Justice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Justice Ayesha A. Malik', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Justices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., C.A. 3/2016 or case title', max_length=500)),
                ('case_number', models.CharField(blank=True, help_text='Extracted case number if available', max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('pdf_file', models.FileField(max_length=1000, upload_to=legal_library.models.judgment_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('justice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='legal_library.justice')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
